# An action used to request the download of a YouTube video's audio

# Constants to define allowable qualities for the download
uint8 QUALITY_UNSET=0
uint8 QUALITY_64=1
uint8 QUALITY_128=2
uint8 QUALITY_192=3
uint8 QUALITY_256=4
uint8 QUALITY_320=5

# The ID of the video to download, uniquely identified by YouTube
string video_id
# The list of desired file formats to download the audio to
sh_common_interfaces/StringArr file_formats
# The desired download quality
uint8 quality
---
# The absolute file paths as a result of the download
# There is a 1 to 1 correlation between this and the formats in the request,
# if creating a file of a specified format failed, then the string is empty
# The codec, etc. can be extrapolated from each file extension
sh_common_interfaces/StringArr local_urls
---
# The status of the download, as a percentage in the domain [0,100]
float64 completion
