# An action used to play a sound file by file name

# The characteristics found of the audio at the specified URL
LabeledAudioCharacteristics labeled_audio_characteristics
---
# Whether or not this playback finished because of a STOP command
bool was_stopped
---
# An update on the sound file as it plays
PlaybackUpdate update
